
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

require("monitors")
require("autostart")
require("environment")
require("permissions")
require("look")
require("input")
require("workspaces")

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
-- local terminal    = "alacritty"
local terminal = "alacritty -e zsh"
local browser = "brave"
local fileManager = "nautilus"
local menu = os.getenv("HOME") .. "/.config/rofi/launchers/type-2/launcher.sh"


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + Q", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("hyprctl dispatch exit"))
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Making a Screenshot

hl.bind("Print",hl.dsp.exec_cmd([[FILE="$HOME/Pictures/Screenshots/$(date +%F-%H%M%S).png"; mkdir -p "$HOME/Pictures/Screenshots"; grim -g "$(slurp)" "$FILE" && wl-copy < "$FILE"]]))

-- Lid switch
----------------------------------------------
-- if we switch to running ashell as service
-- replace 'pkill ashell ashell &' with 'systemctl --user restart ashell'
-- to run it as a service
-- mkdir -p ~/.config/systemd/user
-- nano ~/.config/systemd/user/ashell.service
-- put the following into the ashell.service

-------------------
-- [Unit]
-- Description=ashell status bar
-- After=graphical-session.target

-- [Service]
-- ExecStart=/usr/bin/ashell
-- Restart=on-failure
-- RestartSec=2

-- [Install]
-- WantedBy=default.target
-------------------

-- Then run
-- systemctl --user daemon-reload
-- systemctl --user enable --now ashell.service
-- Check it with
-- systemctl --user status ashell
-- Then remove the ashell launch line from autostart.lua
-- Finally, replace this in your lid bindings as indicated at the top of this instruction
-- replace 'pkill ashell ashell &' with 'systemctl --user restart ashell'
----------------------------------------------

hl.bind(
    "switch:on:Lid Switch",
    hl.dsp.exec_cmd([[sh -c '
        if [ "$(hyprctl monitors | grep -c "^Monitor")" -gt 1 ]; then
            hyprctl eval '\''hl.monitor({ output = "eDP-1", disabled = true })'\''
            sleep 1
            pkill ashell
            ashell &
        else
            systemctl suspend
        fi
    ']]),
    { locked = true }
)

hl.bind(
    "switch:off:Lid Switch",
    hl.dsp.exec_cmd([[sh -c '
        hyprctl eval '\''hl.monitor({ output = "eDP-1", disabled = false, mode = "preferred", position = "auto", scale = 1.2 })'\''
        sleep 1
        pkill ashell
        ashell &
    ']]),
    { locked = true }
)
